### PR TITLE
[PLAT-6415] Integrate with dominodatalab/repo-standards CircleCI orb

### PR DESCRIPTION
**Pull request by urianchang**
# What this PR does / why we need it
We've created a CircleCI orb to help standardize how CI builds and publishes Docker images. For more background information, please see: https://dominodatalab.atlassian.net/wiki/spaces/ENG/pages/2424700959/Repository+Standards.

# Special notes for your reviewer
NOTE: The two images that are created in CI: `quay.io/domino/seldon-core-executor` and `quay.io/domino/seldon-core-operator` are based on `distroless` images.

As part of the rollout of the orb, some of the tasks that we will do are:

- [x] Has OSRP comment
- [x] Has OSRP update steps
- [x] Conform to tagging
- [x] .github/CODEOWNERS exists with current team
- [x] Integrate package-docker job
- [x] Add BUILD_CACHE_VERSION environment variable to CircleCI project settings.
- [x] CircleCI filters match the repo standards repo type
- [x] Docker inspect before and after image

### seldon-core-operator
```
> docker inspect quay.io/domino/seldon-core-operator:1.15.0-2bbea250e > before
> docker inspect quay.io/domino/seldon-core-operator:uchang.14db6827dd3a225c32b1c1176225fb766f5a1f57 > after
> diff -y before after
[								[
    {								    {
        "Id": "sha256:7b9db9d828bd8e0e401035c5009e24965fdacbb |	        "Id": "sha256:75ddd13210f39c5b3ccaf77522e1e4162e06e29
        "RepoTags": [						        "RepoTags": [
            "quay.io/domino/seldon-core-operator:1.15.0-2bbea |	            "quay.io/domino/seldon-core-operator:uchang.14db6
        ],							        ],
        "RepoDigests": [					        "RepoDigests": [
            "quay.io/domino/seldon-core-operator@sha256:ff258 |	            "quay.io/domino/seldon-core-operator@sha256:a3d42
        ],							        ],
        "Parent": "",						        "Parent": "",
        "Comment": "",					      |	        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-02-17T14:46:11.555831941Z",	      |	        "Created": "2023-03-20T18:03:13.88535339Z",
        "Container": "3fa7fba6839feba7d9991225e4cffdf743cbb31 |	        "Container": "",
        "ContainerConfig": {					        "ContainerConfig": {
            "Hostname": "3fa7fba6839f",			      |	            "Hostname": "",
            "Domainname": "",					            "Domainname": "",
            "User": "65532",				      |	            "User": "",
            "AttachStdin": false,				            "AttachStdin": false,
            "AttachStdout": false,				            "AttachStdout": false,
            "AttachStderr": false,				            "AttachStderr": false,
            "Tty": false,					            "Tty": false,
            "OpenStdin": false,					            "OpenStdin": false,
            "StdinOnce": false,					            "StdinOnce": false,
            "Env": [					      |	            "Env": null,
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbi |	            "Cmd": null,
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates |	            "Image": "",
            ],						      <
            "Cmd": [					      <
                "/bin/sh",				      <
                "-c",					      <
                "#(nop) ",				      <
                "ENTRYPOINT [\"/manager\"]"		      <
            ],						      <
            "Image": "sha256:aea14214de21ca37be7f033318534038 <
            "Volumes": null,					            "Volumes": null,
            "WorkingDir": "/",				      |	            "WorkingDir": "",
            "Entrypoint": [				      |	            "Entrypoint": null,
                "/manager"				      <
            ],						      <
            "OnBuild": null,					            "OnBuild": null,
            "Labels": {					      |	            "Labels": null
                "author": "",				      <
                "build": "https://circleci.com/gh/cerebrotech <
                "commit-sha": "23feb17528cc1f6c8e092bea166f49 <
                "maintainer": "eng-devprod@dominodatalab.com" <
                "upstream_dockerfile": "https://github.com/Go <
                "vendoring_dockerfile": "https://github.com/c <
            }						      <
        },							        },
        "DockerVersion": "20.10.14",			      |	        "DockerVersion": "",
        "Author": "",					      |	        "Author": "Bazel",
        "Config": {						        "Config": {
            "Hostname": "",					            "Hostname": "",
            "Domainname": "",					            "Domainname": "",
            "User": "65532",					            "User": "65532",
            "AttachStdin": false,				            "AttachStdin": false,
            "AttachStdout": false,				            "AttachStdout": false,
            "AttachStderr": false,				            "AttachStderr": false,
            "Tty": false,					            "Tty": false,
            "OpenStdin": false,					            "OpenStdin": false,
            "StdinOnce": false,					            "StdinOnce": false,
            "Env": [						            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbi	                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbi
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates	                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates
            ],							            ],
            "Cmd": null,					            "Cmd": null,
            "Image": "sha256:aea14214de21ca37be7f033318534038 |	            "Image": "",
            "Volumes": null,					            "Volumes": null,
            "WorkingDir": "/",					            "WorkingDir": "/",
            "Entrypoint": [					            "Entrypoint": [
                "/manager"					                "/manager"
            ],							            ],
            "OnBuild": null,					            "OnBuild": null,
            "Labels": {						            "Labels": {
                "author": "",					                "author": "",
                "build": "https://circleci.com/gh/cerebrotech	                "build": "https://circleci.com/gh/cerebrotech
							      >	                "com.dominodatalab.ci.build-url": "https://ci
							      >	                "com.dominodatalab.image.dockerfile": "https:
                "commit-sha": "23feb17528cc1f6c8e092bea166f49	                "commit-sha": "23feb17528cc1f6c8e092bea166f49
                "maintainer": "eng-devprod@dominodatalab.com"	                "maintainer": "eng-devprod@dominodatalab.com"
							      >	                "org.opencontainers.image.authors": "github_t
							      >	                "org.opencontainers.image.revision": "14db682
							      >	                "org.opencontainers.image.source": "https://g
							      >	                "quay.expires-after": "5w",
                "upstream_dockerfile": "https://github.com/Go	                "upstream_dockerfile": "https://github.com/Go
                "vendoring_dockerfile": "https://github.com/c	                "vendoring_dockerfile": "https://github.com/c
            }							            }
        },							        },
        "Architecture": "amd64",				        "Architecture": "amd64",
        "Os": "linux",						        "Os": "linux",
        "Size": 169156871,				      |	        "Size": 169852596,
        "VirtualSize": 169156871,			      |	        "VirtualSize": 169852596,
        "GraphDriver": {					        "GraphDriver": {
            "Data": {						            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/08eadcd |	                "LowerDir": "/var/lib/docker/overlay2/f2682ef
                "MergedDir": "/var/lib/docker/overlay2/08863c |	                "MergedDir": "/var/lib/docker/overlay2/cafb39
                "UpperDir": "/var/lib/docker/overlay2/08863c2 |	                "UpperDir": "/var/lib/docker/overlay2/cafb396
                "WorkDir": "/var/lib/docker/overlay2/08863c27 |	                "WorkDir": "/var/lib/docker/overlay2/cafb3963
            },							            },
            "Name": "overlay2"					            "Name": "overlay2"
        },							        },
        "RootFS": {						        "RootFS": {
            "Type": "layers",					            "Type": "layers",
            "Layers": [						            "Layers": [
                "sha256:05ef21d763159987b9ec5cfb3377a61c67780	                "sha256:05ef21d763159987b9ec5cfb3377a61c67780
                "sha256:91f7bcfdfda81b6c6e51b8e1da58b48759351	                "sha256:91f7bcfdfda81b6c6e51b8e1da58b48759351
                "sha256:d854cc784a4306dd62b6b1995f24dae08644a |	                "sha256:99660fc1f0e5f0c0f71e8f79e5050f63106cc
                "sha256:404b7301d413f86d3c0ebac2f83b3eeb8e84a |	                "sha256:3ea5f5598c21b589d306574830e9930804cc7
                "sha256:784636ee741b160fc058e2a529e85ded3dede |	                "sha256:3f7ad3c84eabf44a3ba605192ac4824befcc2
                "sha256:8b0ba0651d5ea211a1aec6ec3f735a98be09a |	                "sha256:a7c8a59c65427c4bc16fb6ce3885a94dc5129
                "sha256:4aec1eb3e30fec7899953ebe751d06c56299f |	                "sha256:803eb9c970a5f6874fd977bcdbfb1bb4122a8
                "sha256:7175cd35e7c140b72c6b20a1ba65488fdcbeb |	                "sha256:cb7230911badbb23329aa1b5736f0f81459fc
                "sha256:4b21e9fbfac6bc9cc2e0344b1c9773d82886f |	                "sha256:908602bd4c9f5e633a2e29928e35a2257299f
            ]							            ]
        },							        },
        "Metadata": {						        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"		            "LastTagTime": "0001-01-01T00:00:00Z"
        }							        }
    }								    }
]								]
```

### seldon-core-executor
```
> docker inspect quay.io/domino/seldon-core-executor:1.15.0-2bbea250e > before
> docker inspect quay.io/domino/seldon-core-executor:uchang.14db6827dd3a225c32b1c1176225fb766f5a1f57 > after
> diff -y before after
[								[
    {								    {
        "Id": "sha256:a9cb2f4ed757d8ad76e9f39fb3553df3e13f291 |	        "Id": "sha256:f597d5626c0a7aba6dca8742f6c8675d829f37a
        "RepoTags": [						        "RepoTags": [
            "quay.io/domino/seldon-core-executor:1.15.0-2bbea |	            "quay.io/domino/seldon-core-executor:uchang.14db6
        ],							        ],
        "RepoDigests": [					        "RepoDigests": [
            "quay.io/domino/seldon-core-executor@sha256:9495b |	            "quay.io/domino/seldon-core-executor@sha256:e16ed
        ],							        ],
        "Parent": "",						        "Parent": "",
        "Comment": "",					      |	        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-02-17T14:51:57.701107953Z",	      |	        "Created": "2023-03-20T18:52:03.664375889Z",
        "Container": "04568038f6d9df9cf02a60ac7939f615d151695 |	        "Container": "",
        "ContainerConfig": {					        "ContainerConfig": {
            "Hostname": "04568038f6d9",			      |	            "Hostname": "",
            "Domainname": "",					            "Domainname": "",
            "User": "65532",				      |	            "User": "",
            "AttachStdin": false,				            "AttachStdin": false,
            "AttachStdout": false,				            "AttachStdout": false,
            "AttachStderr": false,				            "AttachStderr": false,
            "Tty": false,					            "Tty": false,
            "OpenStdin": false,					            "OpenStdin": false,
            "StdinOnce": false,					            "StdinOnce": false,
            "Env": [					      |	            "Env": null,
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbi |	            "Cmd": null,
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates |	            "Image": "",
            ],						      <
            "Cmd": [					      <
                "/bin/sh",				      <
                "-c",					      <
                "#(nop) ",				      <
                "ENTRYPOINT [\"/executor\"]"		      <
            ],						      <
            "Image": "sha256:474b6789987453410025b2ceb5035253 <
            "Volumes": null,					            "Volumes": null,
            "WorkingDir": "/",				      |	            "WorkingDir": "",
            "Entrypoint": [				      |	            "Entrypoint": null,
                "/executor"				      <
            ],						      <
            "OnBuild": null,					            "OnBuild": null,
            "Labels": {					      |	            "Labels": null
                "author": "",				      <
                "build": "https://circleci.com/gh/cerebrotech <
                "commit-sha": "23feb17528cc1f6c8e092bea166f49 <
                "maintainer": "eng-devprod@dominodatalab.com" <
                "upstream_dockerfile": "https://github.com/Go <
                "vendoring_dockerfile": "https://github.com/c <
            }						      <
        },							        },
        "DockerVersion": "20.10.14",			      |	        "DockerVersion": "",
        "Author": "",					      |	        "Author": "Bazel",
        "Config": {						        "Config": {
            "Hostname": "",					            "Hostname": "",
            "Domainname": "",					            "Domainname": "",
            "User": "65532",					            "User": "65532",
            "AttachStdin": false,				            "AttachStdin": false,
            "AttachStdout": false,				            "AttachStdout": false,
            "AttachStderr": false,				            "AttachStderr": false,
            "Tty": false,					            "Tty": false,
            "OpenStdin": false,					            "OpenStdin": false,
            "StdinOnce": false,					            "StdinOnce": false,
            "Env": [						            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbi	                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbi
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates	                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates
            ],							            ],
            "Cmd": null,					            "Cmd": null,
            "Image": "sha256:474b6789987453410025b2ceb5035253 |	            "Image": "",
            "Volumes": null,					            "Volumes": null,
            "WorkingDir": "/",					            "WorkingDir": "/",
            "Entrypoint": [					            "Entrypoint": [
                "/executor"					                "/executor"
            ],							            ],
            "OnBuild": null,					            "OnBuild": null,
            "Labels": {						            "Labels": {
                "author": "",					                "author": "",
                "build": "https://circleci.com/gh/cerebrotech	                "build": "https://circleci.com/gh/cerebrotech
							      >	                "com.dominodatalab.ci.build-url": "https://ci
							      >	                "com.dominodatalab.image.dockerfile": "https:
                "commit-sha": "23feb17528cc1f6c8e092bea166f49	                "commit-sha": "23feb17528cc1f6c8e092bea166f49
                "maintainer": "eng-devprod@dominodatalab.com"	                "maintainer": "eng-devprod@dominodatalab.com"
							      >	                "org.opencontainers.image.authors": "github_t
							      >	                "org.opencontainers.image.revision": "14db682
							      >	                "org.opencontainers.image.source": "https://g
							      >	                "quay.expires-after": "5w",
                "upstream_dockerfile": "https://github.com/Go	                "upstream_dockerfile": "https://github.com/Go
                "vendoring_dockerfile": "https://github.com/c	                "vendoring_dockerfile": "https://github.com/c
            }							            }
        },							        },
        "Architecture": "amd64",				        "Architecture": "amd64",
        "Os": "linux",						        "Os": "linux",
        "Size": 169816350,				      |	        "Size": 171019028,
        "VirtualSize": 169816350,			      |	        "VirtualSize": 171019028,
        "GraphDriver": {					        "GraphDriver": {
            "Data": {						            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/3837242 |	                "LowerDir": "/var/lib/docker/overlay2/9c7a3b1
                "MergedDir": "/var/lib/docker/overlay2/b86517 |	                "MergedDir": "/var/lib/docker/overlay2/7a21a7
                "UpperDir": "/var/lib/docker/overlay2/b865172 |	                "UpperDir": "/var/lib/docker/overlay2/7a21a7e
                "WorkDir": "/var/lib/docker/overlay2/b8651726 |	                "WorkDir": "/var/lib/docker/overlay2/7a21a7e9
            },							            },
            "Name": "overlay2"					            "Name": "overlay2"
        },							        },
        "RootFS": {						        "RootFS": {
            "Type": "layers",					            "Type": "layers",
            "Layers": [						            "Layers": [
                "sha256:05ef21d763159987b9ec5cfb3377a61c67780	                "sha256:05ef21d763159987b9ec5cfb3377a61c67780
                "sha256:91f7bcfdfda81b6c6e51b8e1da58b48759351	                "sha256:91f7bcfdfda81b6c6e51b8e1da58b48759351
                "sha256:b8a9695c8c24d5a4bdbb12d8c6a26ca520157 |	                "sha256:d9e68c5922324f0abdc76800f6622f0106851
                "sha256:af6516a478b6a619da54c6f3fc95d4c0f6560 |	                "sha256:a14e91bbad03a5a7208daae2faa71a31c353d
                "sha256:07e3bed2ee3b31616e596b399cf5a6de67e0c |	                "sha256:f0b54dbf526c9ec30ae0aa068ba37b69c5d13
                "sha256:fcd85a3fc0acc87c3da052986e78a2a043d81 |	                "sha256:ed1d98a09fe9a8326e88685d70d047c147325
            ]							            ]
        },							        },
        "Metadata": {						        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"		            "LastTagTime": "0001-01-01T00:00:00Z"
        }							        }
    }								    }
]								]
```

### CODE REVIEW

**Comment by ddl-jbrown** [comment]
@ddl-kartik-mathur @dmcwhorter-ddl @jradchenko Can you review at your earliest convenience?

**Comment by ddl-kartik-mathur** [comment]
Looks good!
@urianchang We removed a few things from container configs like Env, Cmd, Image etc is that on purpose?

**Comment by urianchang** [comment]
@ddl-kartik-mathur, the changes to `ContainerConfig` should be ok. The config refers to the container that generated the image.

References:
* https://forums.docker.com/t/what-is-the-difference-between-containerconfig-and-config-in-image/83232
* https://stackoverflow.com/questions/36216220/what-is-different-of-config-and-containerconfig-of-docker-inspect

**Comment by ddl-kartik-mathur** [comment]
also, the new tag is uchang.14db6827dd3a225c32b1c1176225fb766f5a1f57, do we have to update our code to use this tag instead? @urianchang

**Review by ddl-kartik-mathur — APPROVED** [review]

**Comment by urianchang** [comment]
@ddl-kartik-mathur, after merging to `rabbitmq` branch, I'll need to create a new tag and update the 5.6.0 image catalog. 

```
  seldon_core_executor:
    registry: quay.io
    repository: domino/seldon-core-executor
    tag: 1.15.0-domino-dev-rabbitmq.latest
  seldon_core_operator:
    registry: quay.io
    repository: domino/seldon-core-operator
    tag: 1.15.0-domino-dev-rabbitmq.latest
```

Do you want me to merge the `rabbitmq-1.1.x` branch into `rabbitmq` as well: https://github.com/dominodatalab/seldon-core/compare/rabbitmq...dominodatalab:seldon-core:rabbitmq-1.1.x? Looks like the missing commit is updating the base image (for OSRP?).

**Comment by urianchang** [comment]
Ok, I'll merge that branch in, since it looks like we're using that image in the 5.5.1 catalog.

```
  seldon_core_executor:
    registry: quay.io
    repository: domino/seldon-core-executor
    tag: 1.15.0-dev-rabbitmq-1.1.0
  seldon_core_operator:
    registry: quay.io
    repository: domino/seldon-core-operator
    tag: 1.15.0-dev-rabbitmq-1.1.0
```

**Update**: PR - https://github.com/dominodatalab/seldon-core/pull/23

**Comment by dmcwhorter-ddl** [comment]
Hmm, I think this works but its pushing us further away from running the build as the seldon repo does, since we're not using `make docker-build` as they do.
We also use the `domino-build.sh` script for local development and to tag releases.
Is there a way to use the orb to tag/push the image after its built rather than having it call the docker build steps directly?

**Comment by urianchang** [comment]
After discussing it with the team, we're going to go with another alternative. Closing this PR and https://github.com/dominodatalab/seldon-core/pull/23

**Pull request closed without merging**
